version: '3'

services:
  app-server:
    build: .cloud/docker
    image: laravel-app
    depends_on:
      - mysql
#      - mysql-test
      - sqlite
      - redis
    volumes:
      - ./:/application:cached

  horizon:
    build: .cloud/docker
    image: laravel-app
    command: php artisan horizon
    depends_on:
      - mysql
    volumes:
      - ./:/application:cached

  mysql:
    image: mysql:8
    command: --default-authentication-plugin=mysql_native_password
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=secret
      - MYSQL_DATABASE=laravel_app
    volumes:
      - db-data:/var/lib/mysql:cached

#  mysql-test:
#    image: mysql:8
#   command: --default-authentication-plugin=mysql_native_password
#    ports:
#      - "3308:3306"
#    environment:
#      - MYSQL_ROOT_PASSWORD=secret
#      - MYSQL_DATABASE=testing

  sqlite:
    image: nouchka/sqlite3:latest
    stdin_open: true
    tty: true
    volumes:
      - ./db/:/root/db/

  nginx:
    image: nginx:latest
    build:
      context: .
      dockerfile: .cloud/nginx/Dockerfile
    restart: always
    ports:
      - "8000:80"
      - "4443:443"
    volumes:
      - .cloud/nginx/nginx.conf:/etc/nginx/conf.d/default.conf:cached
      - ./:/application:cached
    depends_on:
      - app-server

  redis:
    image: redis:alpine
    ports:
      - "6380:6379"

volumes:
  db-data:
